### ISSUE TITLE
Windows 64 build

### ISSUE THREAD

**Issue by zmarty** [insomniacslk/dublin-traceroute#19]
Can you please create a Win 64 build?

Thanks!

**Comment by insomniacslk** [comment]
Hey @zmarty , I don't have a Windows machine for development unfortunately. I'd be happy to host a binary build if you feel like contributing it.

For the record, a few months ago I had a chance to compile dublin-traceroute under Bash-on-Windows, and it went fine, but when running it, it failed at creating raw sockets, even when run as Administrator (plus `sudo` inside). There are a few known bugs on the topic, see https://github.com/Microsoft/BashOnWindows/issues/18 and https://github.com/Microsoft/BashOnWindows/issues/1743. It's claimed to be fixed in the Insider Build, but I have no way to verify.

**Comment by zmarty** [comment]
Yeah I pretty much had the same problem with Bash on Windows. Even if they get this to work I don't feel very comfortable using an extra layer of code translation, since it might affect latency readings.

**Comment by insomniacslk** [comment]
I guess we will not have a build for Windows anytime soon then
