### ISSUE TITLE
About the '*' misterious node names

### ISSUE THREAD

**Issue by h3ct0r** [insomniacslk/dublin-traceroute#32]
Hi,

First, I would like to thank you guys for making available/open sourcing this tool (and taking the effort to create a nice documentation).

Sometimes the trace gives a ' * ' name to some terminal nodes, as observable in the toy example of the image attached. Is this normal?

![trace_local_192 168 0 7](https://user-images.githubusercontent.com/2656938/43052941-4038b068-8e00-11e8-8835-7f13b3749323.png)

In this scenario is safe to assume that the ' * ' is in fact '192.168.0.7'? 
Or It's safe to assume that always that a ' * ' and the destination node is found we could merge those two?

**Comment by insomniacslk** [comment]
Hello @h3ct0r, happy that you like the tool!

There is some further documentation on https://blog.dublin-traceroute.net , which I would recommend you to read as it explains step by step how things are done. I can write more posts if you have a specific request.

In your specific example, the `*` represents a missing response to a probe packet that should be located at that layer. In particular, dublin-traceroute did not receive a response for most of the packets that have been sent with TTL 2, so that diagram means "I've sent 20 packets on different port combinations, but only two replied at TTL 2, dst port 33434 and 33451".

As to why this happens, again you can look at the blog posts, but I guess that 192.168.0.7 simply didn't respond in time (slow or overloaded?). A way to find out could be to increase the inter-packet delay, which basically gives more time to that host to respond.

If you think the host is fine, and you suspect a bug, please take a packet dump of the traceroute, using the filter `udp portrange 33434-33464 or (icmp[icmptype] == 3 and (icmp[icmpcode] == 3 or icmp[icmpcode] == 4)) or (icmp[icmptype] == 11 and icmp[icmpcode] == 0)` and we can troubleshoot it. Adjust the port range to whatever you are actually using

**Comment by h3ct0r** [comment]
Hi @insomniacslk, thank you for the response. I did read the blog, very informative! :)
I will try to make a more detailed analysis, but for now, we can set this issue as closed!

Thanks again!
